register:
  path: /api/v1/register
  controller: App\Controller\Api\v1\AuthController::register
  methods: POST

api_login:
  path: /api/v1/login
  methods:  [POST]

test:
  path: /api/v1/test
  controller: App\Controller\Api\v1\AuthController::test