register:
  path: /api/v1/register
  controller: App\Controller\Api\v1\AuthController::register
  methods: POST

api_login:
  path: /api/v1/login
  methods:  [POST]

test:
  path: /api/v1/test
  controller: App\Controller\Api\v1\AuthController::test

api_v1:
  prefix: /api/v1
  resource: '../src/Controller/Api/v1'

web:
  prefix: /
  resource: '../src/Controller/Web'